
// department 
export const FETCH_DEAPRTMENT = 'FETCH_DEAPRTMENT';
export const ADD_DEAPRTMENT = 'ADD_DEAPRTMENT';
export const EDIT_DEAPRTMENT = 'EDIT_DEAPRTMENT';
export const DELETE_DEAPRTMENT = 'DELETE_DEAPRTMENT';
export const UPDATE_DEAPRTMENT = 'UPDATE_DEAPRTMENT';
export const FILTER_DEPARTMENT = 'FILTER_DEPARTMENT';



export const FETCH_LEARNCLASS = 'FETCH_LEARNCLASS';
export const ADD_LEARNCLASS = 'ADD_LEARNCLASS';
export const EDIT_LEARNCLASS = 'EDIT_LEARNCLASS';
export const DELETE_LEARNCLASS = 'DELETE_LEARNCLASS';
export const UPDATE_LEARNCLASS = 'UPDATE_LEARNCLASS';
export const FILTER_LEARNCLASS = 'FILTER_LEARNCLASS';
