
// department 
export const FETCH_DEAPRTMENT = 'FETCH_DEAPRTMENT';
export const ADD_DEAPRTMENT = 'ADD_DEAPRTMENT';
export const EDIT_DEAPRTMENT = 'EDIT_DEAPRTMENT';
export const DELETE_DEAPRTMENT = 'DELETE_DEAPRTMENT';
export const UPDATE_DEAPRTMENT = 'UPDATE_DEAPRTMENT';
export const FILTER_DEPARTMENT = 'FILTER_DEPARTMENT';


// learn class
export const FETCH_LEARNCLASS = 'FETCH_LEARNCLASS';
export const ADD_LEARNCLASS = 'ADD_LEARNCLASS';
export const EDIT_LEARNCLASS = 'EDIT_LEARNCLASS';
export const DELETE_LEARNCLASS = 'DELETE_LEARNCLASS';
export const UPDATE_LEARNCLASS = 'UPDATE_LEARNCLASS';
export const FILTER_LEARNCLASS = 'FILTER_LEARNCLASS';



// student
export const FETCH_STUDENT = 'FETCH_STUDENT';
export const ADD_STUDENT = 'ADD_STUDENT';
export const EDIT_STUDENT = 'EDIT_STUDENT';
export const DELETE_STUDENT = 'DELETE_STUDENT';
export const UPDATE_STUDENT = 'UPDATE_STUDENT';
export const FILTER_STUDENT = 'FILTER_STUDENT';
export const GET_ATTENDANCESHEET = 'GET_ATTENDANCESHEET';
// export const FILTER_STUDENT = 'FILTER_STUDENT';

// Specailized
export const FETCH_SPECAILIZED = 'FETCH_SPECAILIZED';
export const ADD_SPECAILIZED = 'ADD_SPECAILIZED';
export const EDIT_SPECAILIZED = 'EDIT_SPECAILIZED';
export const DELETE_SPECAILIZED = 'DELETE_SPECAILIZED';
export const UPDATE_SPECAILIZED = 'UPDATE_SPECAILIZED';
export const FILTER_SPECAILIZED = 'FILTER_SPECAILIZED';


// learnyear 
export const FETCH_LEARNYEAR = 'FETCH_LEARNYEAR';
export const ADD_LEARNYEAR = 'ADD_LEARNYEAR';
export const EDIT_LEARNYEAR = 'EDIT_LEARNYEAR';
export const DELETE_LEARNYEAR = 'DELETE_LEARNYEAR';
export const UPDATE_LEARNYEAR = 'UPDATE_LEARNYEAR';
export const FILTER_LEARNYEAR = 'FILTER_LEARNYEAR';

// subject 
export const FETCH_SUBJECT = 'FETCH_SUBJECT';
export const ADD_SUBJECT = 'ADD_SUBJECT';
export const EDIT_SUBJECT = 'EDIT_SUBJECT';
export const DELETE_SUBJECT = 'DELETE_SUBJECT';
export const UPDATE_SUBJECT = 'UPDATE_SUBJECT';
export const FILTER_SUBJECT = 'FILTER_SUBJECT';



// position
export const FETCH_POSITION = 'FETCH_POSITION';
export const ADD_POSITION = 'ADD_POSITION';
export const EDIT_POSITION = 'EDIT_POSITION';
export const DELETE_POSITION = 'DELETE_POSITION';
export const UPDATE_POSITION = 'UPDATE_POSITION';
export const FILTER_POSITION = 'FILTER_POSITION';

// pointstudent
export const FETCH_POINTSTUDENT = 'FETCH_POINTSTUDENT';
export const ADD_POINTSTUDENT = 'ADD_POINTSTUDENT';
export const EDIT_POINTSTUDENT = 'EDIT_POINTSTUDENT';
export const DELETE_POINTSTUDENT = 'DELETE_POINTSTUDENT';
export const UPDATE_POINTSTUDENT = 'UPDATE_POINTSTUDENT';
export const FILTER_POINTSTUDENT = 'FILTER_POINTSTUDENT';

// login 
export const GET_ERRORS = 'GET_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';


//Account 

export const FETCH_ACCOUNT = 'FETCH_ACCOUNT';
export const ADD_ACCOUNT = 'ADD_ACCOUNT';
export const DELETE_ACCOUNT = 'DELETE_ACCOUNT';

//role 
export const FETCH_ROLE = 'FETCH_ROLE';

//attendancesheet
export const FETCH_ATTENDANCESHEET = 'FETCH_ATTENDANCESHEET';
export const ADD_ATTENDANCESHEET = 'ADD_ATTENDANCESHEET';
export const EDIT_ATTENDANCESHEET = 'EDIT_ATTENDANCESHEET';
export const DELETE_ATTENDANCESHEET = 'DELETE_ATTENDANCESHEET';
export const UPDATE_ATTENDANCESHEET = 'UPDATE_ATTENDANCESHEET';
export const FILTER_ATTENDANCESHEET = 'FILTER_ATTENDANCESHEET';

// semester

export const FETCH_SEMESTER = 'FETCH_SEMESTER';
export const ADD_SEMESTER = 'ADD_SEMESTER';
export const EDIT_SEMESTER = 'EDIT_SEMESTER';
export const DELETE_SEMESTER = 'DELETE_SEMESTER';
export const UPDATE_SEMESTER = 'UPDATE_SEMESTER';
export const FILTER_SEMESTER = 'FILTER_SEMESTER';
