export default {
    GET_DEPARTMENT: "GET_DEPARTMENT",
    GET_DEPARTMENT_FAILURE:'GET_DEPARTMENT_FAILURE',
    INSERT_DEPARTMENT: "INSERT_DEPARTMENT",
    INSERT_INVOICE_FAILURE:"INSERT_INVOICE_FAILURE",

    UPDATE_DEPARTMENT:"UPDATE_DEPARTMENT",
    DELETE_DEPARTMENT: "DELETE_DEPARTMENT",
    DELETE_DEPARTMENT_FAILURE:'DELETE_DEPARTMENT_FAILURE',

};
