
// department 
export const FETCH_DEAPRTMENT = 'FETCH_DEAPRTMENT';
export const ADD_DEAPRTMENT = 'ADD_DEAPRTMENT';
export const EDIT_DEAPRTMENT = 'EDIT_DEAPRTMENT';
export const DELETE_DEAPRTMENT = 'DELETE_DEAPRTMENT';
export const UPDATE_DEAPRTMENT = 'UPDATE_DEAPRTMENT';
export const FILTER_DEPARTMENT = 'FILTER_DEPARTMENT';


// learn class
export const FETCH_LEARNCLASS = 'FETCH_LEARNCLASS';
export const ADD_LEARNCLASS = 'ADD_LEARNCLASS';
export const EDIT_LEARNCLASS = 'EDIT_LEARNCLASS';
export const DELETE_LEARNCLASS = 'DELETE_LEARNCLASS';
export const UPDATE_LEARNCLASS = 'UPDATE_LEARNCLASS';
export const FILTER_LEARNCLASS = 'FILTER_LEARNCLASS';



// student
export const FETCH_STUDENT = 'FETCH_STUDENT';
export const ADD_STUDENT = 'ADD_STUDENT';
export const EDIT_STUDENT = 'EDIT_STUDENT';
export const DELETE_STUDENT = 'DELETE_STUDENT';
export const UPDATE_STUDENT = 'UPDATE_STUDENT';
export const FILTER_STUDENT = 'FILTER_STUDENT';

// Specailized
export const FETCH_SPECAILIZED = 'FETCH_SPECAILIZED';
export const ADD_SPECAILIZED = 'ADD_SPECAILIZED';
export const EDIT_SPECAILIZED = 'EDIT_SPECAILIZED';
export const DELETE_SPECAILIZED = 'DELETE_SPECAILIZED';
export const UPDATE_SPECAILIZED = 'UPDATE_SPECAILIZED';
export const FILTER_SPECAILIZED = 'FILTER_SPECAILIZED';


// learnyear 
export const FETCH_LEARNYEAR = 'FETCH_LEARNYEAR';
export const ADD_LEARNYEAR = 'ADD_LEARNYEAR';
export const EDIT_LEARNYEAR = 'EDIT_LEARNYEAR';
export const DELETE_LEARNYEAR = 'DELETE_LEARNYEAR';
export const UPDATE_LEARNYEAR = 'UPDATE_LEARNYEAR';
export const FILTER_LEARNYEAR = 'FILTER_LEARNYEAR';

// subject 
export const FETCH_SUBJECT = 'FETCH_SUBJECT';
export const ADD_SUBJECT = 'ADD_SUBJECT';
export const EDIT_SUBJECT = 'EDIT_SUBJECT';
export const DELETE_SUBJECT = 'DELETE_SUBJECT';
export const UPDATE_SUBJECT = 'UPDATE_SUBJECT';
export const FILTER_SUBJECT = 'FILTER_SUBJECT';



// position
export const FETCH_POSITION = 'FETCH_POSITION';
export const ADD_POSITION = 'ADD_POSITION';
export const EDIT_POSITION = 'EDIT_POSITION';
export const DELETE_POSITION = 'DELETE_POSITION';
export const UPDATE_POSITION = 'UPDATE_POSITION';
export const FILTER_POSITION = 'FILTER_POSITION';
